import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "../lib/Providers";
import WishListContextProvider from "./(context)/WishListContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased *:selection:bg-white *:selection:text-black`}
      >
        <Providers>
          <Navbar />
          <WishListContextProvider>
            <main className="min-h-screen">{children}</main>
          </WishListContextProvider>
          <Toaster className="" />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
